/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbd_sqlite;


import java.util.Vector;
import javax.swing.JTextField;

/**
 *
 * @author IsaacDavid
 */
public class MainPage extends javax.swing.JFrame {

    DBManager dbm;
    Login log;
    
    
    
    
    
    /**
     * Creates new form MainPage
     */
    public MainPage(DBManager D, Login LG) {
        initComponents();
        dbm = D;
        log = LG;
        log.setVisible(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Show_ComboBox = new javax.swing.JComboBox<>();
        Show_Button = new javax.swing.JButton();
        Update_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Show_Table = new javax.swing.JTable();
        ShowTable_Button = new javax.swing.JButton();
        Edit_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Show_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tables", "Indexes", "Triggers", "Views" }));
        Show_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_ComboBoxActionPerformed(evt);
            }
        });

        Show_Button.setText("Show");
        Show_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_ButtonMouseClicked(evt);
            }
        });

        Update_Button.setText("Update");

        Show_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Show_Table);

        ShowTable_Button.setText("Show Table");
        ShowTable_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTable_ButtonMouseClicked(evt);
            }
        });

        Edit_Button.setText("Edit");

        Delete_Button.setText("Delete Entry");
        Delete_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_ButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Show_Button)
                        .addGap(34, 34, 34)
                        .addComponent(Update_Button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(ShowTable_Button)
                        .addGap(60, 60, 60)
                        .addComponent(Edit_Button)
                        .addGap(64, 64, 64)
                        .addComponent(Delete_Button)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show_Button)
                    .addComponent(Update_Button))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowTable_Button)
                    .addComponent(Edit_Button)
                    .addComponent(Delete_Button))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Show", jPanel1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Table", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Trigger", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Index", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("View", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Create", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DDL", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("UPDATE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_ButtonMouseClicked
        // TODO add your handling code here:

        String selectedText = Show_Table.getValueAt(Show_Table.getSelectedRow(),2).toString();
        
        String selectedTextforIndex = Show_Table.getValueAt(Show_Table.getSelectedRow(),1).toString();

        int selectedColumn = Show_Table.getSelectedColumn();

        System.out.println(selectedText);

        int selectedIndex = Show_ComboBox.getSelectedIndex();

        try
        {
            if(selectedIndex==0)
            {
                dbm.executeSQL(dbm.deleteTable(selectedText));
                System.out.println(selectedText+" deleted !");
            }
            
            else if(selectedIndex==1)
            {
                dbm.executeSQL(dbm.deleteIndex(selectedTextforIndex));
                System.out.println(selectedTextforIndex+" deleted !");
            }
            
            else if(selectedIndex==2)
            {
                dbm.executeSQL(dbm.deleteTrigger(selectedTextforIndex));
                System.out.println(selectedTextforIndex+" deleted !");
            }
            
            else if(selectedIndex==3)
            {
                dbm.executeSQL(dbm.deleteView(selectedTextforIndex));
                System.out.println(selectedTextforIndex+" deleted !");
            }
            

        }catch(Exception e)
        {
            System.out.println("Error in deleting");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Delete_ButtonMouseClicked

    private void ShowTable_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTable_ButtonMouseClicked
        // TODO add your handling code here:
        String tableName = Show_Table.getValueAt(Show_Table.getSelectedRow(),2)
        .toString();

        int option = Show_ComboBox.getSelectedIndex();

        try
        {
            if(option==0)
            {
                dbm.populateTable(Show_Table, dbm.showTable(tableName));
            }

            if(option==3)
            {
                dbm.populateTable(Show_Table, dbm.showView(tableName));
            }

        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowTable_ButtonMouseClicked

    private void Show_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_ButtonMouseClicked
        // TODO add your handling code here:
        int option = Show_ComboBox.getSelectedIndex();

        //0-tables
        //1-indexes
        //2-triggers
        //3-views

        try
        {
            if(option==0)
            {
                dbm.populateTable(Show_Table, dbm.showTables());
            }

            else if(option==1)
            {
                dbm.populateTable(Show_Table, dbm.showIndexes());
            }

            else if(option==2)
            {
                dbm.populateTable(Show_Table, dbm.showTriggers());
            }
            else if(option==3)
            {
                dbm.populateTable(Show_Table, dbm.showViews());
            }

        }catch(Exception e)
        {
            System.out.println("Error in executing a show function \n");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Show_ButtonMouseClicked

    private void Show_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Show_ComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JButton ShowTable_Button;
    private javax.swing.JButton Show_Button;
    private javax.swing.JComboBox<String> Show_ComboBox;
    private javax.swing.JTable Show_Table;
    private javax.swing.JButton Update_Button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
