/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gbd_sqlite;


import java.awt.Component;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author IsaacDavid
 */
public class MainPage extends javax.swing.JFrame {

    DBManager dbm;
    Login log;
    private Component frame;
    
    
    
    
    
    /**
     * Creates new form MainPage
     */
    public MainPage(DBManager D, Login LG) {
        initComponents();
        dbm = D;
        log = LG;
        log.setVisible(false);
        this.setVisible(true);
    }
    
    private void initComponentValues() throws Exception
    {
       //dbm.populateComboBox(createIndexTablecmb, "select * from sqlite_master;");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Show_ComboBox = new javax.swing.JComboBox<>();
        Show_Button = new javax.swing.JButton();
        Update_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Show_Table = new javax.swing.JTable();
        ShowTable_Button = new javax.swing.JButton();
        Edit_Button = new javax.swing.JButton();
        Delete_Button = new javax.swing.JButton();
        disconnectbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        createTableNametxt = new javax.swing.JTextField();
        createTablebtn = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        createTableFieldAType = new javax.swing.JTextField();
        createTableFieldAType2 = new javax.swing.JTextField();
        createTableFieldAType3 = new javax.swing.JTextField();
        createTableFieldAType4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        createTableFieldBType1 = new javax.swing.JTextField();
        createTableFieldBType2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        createTableFieldCType = new javax.swing.JTextField();
        createTableFieldCType2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createIndextxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        createIndexbtn = new javax.swing.JButton();
        createIndexTabletxt = new javax.swing.JTextField();
        createIndexColumntxt = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        createTriggerNametxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        createTriggerActiontxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CreateTriggerTimetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TriggerCreateTableName = new javax.swing.JTextField();
        createTriggerbtn = new javax.swing.JToggleButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        createViewNametxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        createViewTableName = new javax.swing.JTextField();
        CreateViewbtn = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Show_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tables", "Indexes", "Triggers", "Views" }));
        Show_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_ComboBoxActionPerformed(evt);
            }
        });

        Show_Button.setText("Show");
        Show_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_ButtonMouseClicked(evt);
            }
        });

        Update_Button.setText("Update");

        Show_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Show_Table);

        ShowTable_Button.setText("Show Table");
        ShowTable_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowTable_ButtonMouseClicked(evt);
            }
        });

        Edit_Button.setText("Edit");

        Delete_Button.setText("Delete Entry");
        Delete_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_ButtonMouseClicked(evt);
            }
        });

        disconnectbtn.setText("Disconnect");
        disconnectbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disconnectbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(Show_Button)
                        .addGap(34, 34, 34)
                        .addComponent(Update_Button))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(ShowTable_Button)
                            .addGap(60, 60, 60)
                            .addComponent(Edit_Button)
                            .addGap(64, 64, 64)
                            .addComponent(Delete_Button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(disconnectbtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show_Button)
                    .addComponent(Update_Button))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowTable_Button)
                    .addComponent(Edit_Button)
                    .addComponent(Delete_Button)
                    .addComponent(disconnectbtn))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Show", jPanel1);

        jLabel10.setText("Table Name");

        createTablebtn.setText("Create");
        createTablebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTablebtnMouseClicked(evt);
            }
        });

        jLabel11.setText("Field A type");

        jLabel12.setText("Field B Type");

        jLabel13.setText("Field C Type");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createTablebtn)
                .addGap(26, 26, 26))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createTableFieldCType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createTableFieldBType1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(createTableFieldAType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(createTableNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(createTableFieldAType2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(createTableFieldAType3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(createTableFieldAType4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(createTableFieldBType2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createTableFieldCType2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(createTableNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(createTableFieldAType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTableFieldAType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTableFieldAType3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTableFieldAType4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(createTableFieldBType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTableFieldBType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(createTableFieldCType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTableFieldCType2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(createTablebtn)
                .addGap(21, 21, 21))
        );

        jTabbedPane2.addTab("Table", jPanel5);

        jLabel1.setText("Index Name");

        jLabel2.setText("Table Name");

        jLabel3.setText("Column Name");

        createIndexbtn.setText("Create");
        createIndexbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createIndexbtnMouseClicked(evt);
            }
        });

        createIndexTabletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createIndexTabletxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createIndextxt)
                            .addComponent(createIndexTabletxt)
                            .addComponent(createIndexColumntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createIndexbtn)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(createIndextxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(createIndexTabletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(createIndexColumntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(createIndexbtn)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Index", jPanel6);

        jLabel4.setText("Trigger Name");

        jLabel5.setText("Action");

        jLabel6.setText("Time");

        jLabel7.setText("Table Name");

        createTriggerbtn.setText("Create Trigger");
        createTriggerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createTriggerbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTriggerbtn)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createTriggerNametxt)
                        .addComponent(createTriggerActiontxt)
                        .addComponent(CreateTriggerTimetxt)
                        .addComponent(TriggerCreateTableName, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(createTriggerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CreateTriggerTimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createTriggerActiontxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(69, 69, 69)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TriggerCreateTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(createTriggerbtn)
                .addGap(57, 57, 57))
        );

        jTabbedPane2.addTab("Trigger", jPanel7);

        jLabel8.setText("View Name");

        jLabel9.setText("Table Name");

        CreateViewbtn.setText("Create");
        CreateViewbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateViewbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateViewbtn)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)
                        .addComponent(createViewNametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(createViewTableName)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(createViewNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addComponent(createViewTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(CreateViewbtn)
                .addGap(87, 87, 87))
        );

        jTabbedPane2.addTab("View", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Create", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("DDL", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 845, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("UPDATE", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Delete_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_ButtonMouseClicked
        // TODO add your handling code here:

        String selectedText = Show_Table.getValueAt(Show_Table.getSelectedRow(),2).toString();
        
        String selectedTextforIndex = Show_Table.getValueAt(Show_Table.getSelectedRow(),1).toString();

        int selectedColumn = Show_Table.getSelectedColumn();

        System.out.println(selectedText);

        int selectedIndex = Show_ComboBox.getSelectedIndex();

        try
        {
            if(selectedIndex==0)
            {
                dbm.executeSQL(dbm.deleteTable(selectedText));
                //System.out.println(selectedText+" deleted !");
                JOptionPane.showMessageDialog(frame, selectedText+" deleted!");
            }
            
            else if(selectedIndex==1)
            {
                dbm.executeSQL(dbm.deleteIndex(selectedTextforIndex));
                //System.out.println(selectedTextforIndex+" deleted !");
                JOptionPane.showMessageDialog(frame, selectedTextforIndex+" deleted!");
            }
            
            else if(selectedIndex==2)
            {
                dbm.executeSQL(dbm.deleteTrigger(selectedTextforIndex));
                //System.out.println(selectedTextforIndex+" deleted !");
                JOptionPane.showMessageDialog(frame, selectedTextforIndex+" deleted!");
            }
            
            else if(selectedIndex==3)
            {
                dbm.executeSQL(dbm.deleteView(selectedTextforIndex));
                //System.out.println(selectedTextforIndex+" deleted !");
                JOptionPane.showMessageDialog(frame, selectedTextforIndex+" deleted!");
            }
            

        }catch(Exception e)
        {
            System.out.println("Error in deleting");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Delete_ButtonMouseClicked

    private void ShowTable_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowTable_ButtonMouseClicked
        // TODO add your handling code here:
        String tableName = Show_Table.getValueAt(Show_Table.getSelectedRow(),2)
        .toString();

        int option = Show_ComboBox.getSelectedIndex();

        try
        {
            if(option==0)
            {
                dbm.populateTable(Show_Table, dbm.showTable(tableName));
            }

            if(option==3)
            {
                dbm.populateTable(Show_Table, dbm.showView(tableName));
            }

        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ShowTable_ButtonMouseClicked

    private void Show_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_ButtonMouseClicked
        // TODO add your handling code here:
        int option = Show_ComboBox.getSelectedIndex();

        //0-tables
        //1-indexes
        //2-triggers
        //3-views

        try
        {
            if(option==0)
            {
                dbm.populateTable(Show_Table, dbm.showTables());
            }

            else if(option==1)
            {
                dbm.populateTable(Show_Table, dbm.showIndexes());
            }

            else if(option==2)
            {
                dbm.populateTable(Show_Table, dbm.showTriggers());
            }
            else if(option==3)
            {
                dbm.populateTable(Show_Table, dbm.showViews());
            }

        }catch(Exception e)
        {
            System.out.println("Error in executing a show function \n");
            e.printStackTrace();
        }
    }//GEN-LAST:event_Show_ButtonMouseClicked

    private void Show_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Show_ComboBoxActionPerformed

    private void createIndexbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createIndexbtnMouseClicked
        // TODO add your handling code here:
        String indexName = createIndextxt.getText();
        String tableName = createIndexTabletxt.getText();
        String columnName = createIndexColumntxt.getText();
     
    
        try
        {
            dbm.executeSQL(dbm.createIndex(indexName, tableName, columnName));
            System.out.println(indexName+" created");
        }catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("index could not be created");
        }
        
    }//GEN-LAST:event_createIndexbtnMouseClicked

    private void createIndexTabletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createIndexTabletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createIndexTabletxtActionPerformed

    
    
    //not working
    private void createTriggerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTriggerbtnMouseClicked
        // TODO add your handling code here:
        String triggerName = createTriggerNametxt.getText();
        String triggerTime = CreateTriggerTimetxt.getText();
        String triggerAction = createTriggerActiontxt.getText();
        String triggerDestinationTable = TriggerCreateTableName.getText();
        
         try
        {
            dbm.executeSQL(dbm.createTriggers(triggerName, triggerTime, triggerAction, triggerDestinationTable));
            System.out.println(triggerName+" created");
        }catch(Exception e)
        {
            e.printStackTrace();
            System.out.println("trigger could not be created");
        }
        
    }//GEN-LAST:event_createTriggerbtnMouseClicked

    private void CreateViewbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateViewbtnMouseClicked
        // TODO add your handling code here:
        String viewName = createViewNametxt.getText();
        String viewDestinyTable = createViewTableName.getText();
        
          try
        {
            dbm.executeSQL(dbm.createView(viewName, viewDestinyTable));
            System.out.println(viewName+" created");
        }catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(frame,"View can't be created.","Inane",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_CreateViewbtnMouseClicked

    private void disconnectbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disconnectbtnMouseClicked
        try {
            // TODO add your handling code here:
            dbm.disconnect();
            
        } catch (Exception ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_disconnectbtnMouseClicked

    private void createTablebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createTablebtnMouseClicked
        // TODO add your handling code here:
        
        String tableName = createTableNametxt.getText();
        String fielda = createTableFieldAType.getText();
        String fielda1 = createTableFieldAType2.getText();
        String fielda2 = createTableFieldAType3.getText();
        String fielda3 = createTableFieldAType4.getText();
        String fieldb = createTableFieldBType1.getText();
        String fieldb1 = createTableFieldBType2.getText();
        String fieldc = createTableFieldCType.getText();
        String fieldc1 = createTableFieldCType2.getText();
        
           try
        {
            dbm.executeSQL(dbm.createTables(tableName, fielda, fielda1, fielda2, fielda3, fieldb, fieldb1, fieldc, fieldc1));
            System.out.println(tableName+" created");
        }catch(Exception e)
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(frame,"Table can't be created.","Inane",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_createTablebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CreateTriggerTimetxt;
    private javax.swing.JToggleButton CreateViewbtn;
    private javax.swing.JButton Delete_Button;
    private javax.swing.JButton Edit_Button;
    private javax.swing.JButton ShowTable_Button;
    private javax.swing.JButton Show_Button;
    private javax.swing.JComboBox<String> Show_ComboBox;
    private javax.swing.JTable Show_Table;
    private javax.swing.JTextField TriggerCreateTableName;
    private javax.swing.JButton Update_Button;
    private javax.swing.JTextField createIndexColumntxt;
    private javax.swing.JTextField createIndexTabletxt;
    private javax.swing.JButton createIndexbtn;
    private javax.swing.JTextField createIndextxt;
    private javax.swing.JTextField createTableFieldAType;
    private javax.swing.JTextField createTableFieldAType2;
    private javax.swing.JTextField createTableFieldAType3;
    private javax.swing.JTextField createTableFieldAType4;
    private javax.swing.JTextField createTableFieldBType1;
    private javax.swing.JTextField createTableFieldBType2;
    private javax.swing.JTextField createTableFieldCType;
    private javax.swing.JTextField createTableFieldCType2;
    private javax.swing.JTextField createTableNametxt;
    private javax.swing.JToggleButton createTablebtn;
    private javax.swing.JTextField createTriggerActiontxt;
    private javax.swing.JTextField createTriggerNametxt;
    private javax.swing.JToggleButton createTriggerbtn;
    private javax.swing.JTextField createViewNametxt;
    private javax.swing.JTextField createViewTableName;
    private javax.swing.JButton disconnectbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
